# OS identification from: https://stackoverflow.com/questions/714100/os-detecting-makefile
OS := $(shell uname -s)

ifeq ($(OS), Darwin) 
  CUNIT_PATH_PREFIX = /usr/local/Cellar/cunit/2.1-3
  CUNIT_DIRECTORY = cunit
endif
ifeq ($(OS), Linux) 
  CUNIT_PATH_PREFIX = /util/CUnit
  CUNIT_DIRECTORY = CUnit
endif

CC = gcc
CFLAGS = -g -Wall -std=c11

program.o: program.c
	$(CC) -c $(CFLAGS) program.c

test.o: test.c
	$(CC) -c $(CFLAGS) -I $(CUNIT_PATH_PREFIX)/include/$(CUNIT_DIRECTORY) test.c

runner: runner.c program.o
	$(CC) $(CFLAGS) -o runner program.o runner.c

tests: program.o test.o
	gcc -Wall -L $(CUNIT_PATH_PREFIX)/lib -I $(CUNIT_PATH_PREFIX)/include/$(CUNIT_DIRECTORY) -o tests program.o test.o -lcunit


.PHONY: clean info

clean:
	rm -rf *~ *.o program tests runner *.dSYM

info:
	@echo "User-targets:"
	@echo "\trunner - the executable for the program"
	@echo "\ttests - the executable for the CUnit tests"
	@echo "\tclean - remove Emacs autosave files and files generated by the compiler"
	@echo "\tinfo - print this message"
